/* GENERATED by sync.sh -- do not edit.
 *
 * Give this port's copies of the shared protocol sources their own symbols, so
 * they can never clash with the in-process FujiNet runtime or a sibling port. */
#ifndef NES_FUJINS_H
#define NES_FUJINS_H
#define fujimail_init nes_fujimail_init
#define fujimail_paint nes_fujimail_paint
#define fujimail_read_hotspot nes_fujimail_read_hotspot
#define fujimail_inbound nes_fujimail_inbound
#define fujibus_build_request nes_fujibus_build_request
#define fujibus_parse_reply nes_fujibus_parse_reply
#define fujibus_selftest nes_fujibus_selftest
#endif
