#!/usr/bin/env bash
# sync.sh -- refresh the vendored FujiNet NES cartridge sources.
#
# Usage: ./sync.sh [FN_NES] [FUJINET_CONFIG]
#   FN_NES          fujinet-firmware checkout on nes-bringup (default ~/Workspace/fn-nes)
#   FUJINET_CONFIG  fujinet-config checkout with nes/build/config.nes built
#                   (default ~/Workspace/fujinet-config)
#
# Everything here except FujiNetLink (the transport) is a verbatim copy, plus
# the fujins.h include line that apply.sh adds for MAME. Run it, rebuild,
# commit.

set -euo pipefail
cd "$(dirname "$0")"

FN_NES=${1:-$HOME/Workspace/fn-nes}
CFG=${2:-$HOME/Workspace/fujinet-config}
S="$FN_NES/pico/nes"

cp "$S"/firmware/src/{fujimail.c,fujibus.c,nesmap.c} .
cp "$S"/firmware/include/{fujimail.h,fujibus.h,nesmap.h,fuji_mailbox.h,nes_cart.h,nesloaderrom.h} .

# The real CONFIG, not the cartridge tree's stand-in.
python3 "$S/tools/mkromh.py" "$CFG/nes/build/config.nes" > fujiconfigrom.h

cat > fujins.h <<'EOF'
/* GENERATED by sync.sh -- do not edit.
 *
 * Give this port's copies of the shared protocol sources their own symbols, so
 * they can never clash with the in-process FujiNet runtime or a sibling port. */
#ifndef NES_FUJINS_H
#define NES_FUJINS_H
EOF
for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
           fujibus_build_request fujibus_parse_reply fujibus_selftest; do
    echo "#define $sym nes_$sym" >> fujins.h
done
echo "#endif" >> fujins.h

for f in fujimail.c fujimail.h fujibus.c fujibus.h; do
    if ! head -1 "$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$f")" > "$f.tmp"
        mv "$f.tmp" "$f"
    fi
done

{
    echo "fn-nes:          $(git -C "$FN_NES" rev-parse HEAD)"
    echo "fujinet-config:  $(git -C "$CFG" rev-parse HEAD)"
} > SOURCES
echo "sync.sh: done"
